public class Security_element {

    public UsernameToken_element UsernameToken;

    private String[] usernametoken_type_info = new String[]{'UsernameToken','http://ericsson.com/services/ws_CIL_5/contractcreate',null,'0','1','false'};

    private String[] apex_schema_type_info = new String[]{'http://ericsson.com/services/ws_CIL_5/contractcreate','true','false'};

    private String[] field_order_type_info = new String[]{'UsernameToken'};


}
