public class UsernameToken_element{
    public string Username;
    public string Password;

    private String[] username_type_info = new String[]{'Username','http://ericsson.com/services/ws_CIL_5/contractcreate',null,'0','1','false'};
    private String[] password_type_info = new String[]{'Password','http://ericsson.com/services/ws_CIL_5/contractcreate',null,'0','1','false'};
    private String[] apex_schema_type_info = new String[]{'http://ericsson.com/services/ws_CIL_5/contractcreate','true','false'};
    private String[] field_order_type_info = new String[]{'Username','Password'};
}
